import type { RouteRecordRaw } from 'vue-router'

export type ToolDomain = 'dev' | 'crypto' | 'media' | 'text'
export type NuxtSemanticColor = 'neutral' | 'primary' | 'secondary' | 'success' | 'info' | 'warning' | 'error'
export type ToolStatus = 'stable' | 'beta' | 'experimental'
export type ToolCapability = 'text' | 'file' | 'image' | 'pdf' | 'worker' | 'history' | 'offline'

export interface ToolFeatureDefinition {
  labelKey: string
  keywords?: string[]
  query?: Record<string, string>
}

export interface ToolDefinition {
  name: string
  path: string
  i18nKey: string
  domain: ToolDomain
  icon: string
  color: NuxtSemanticColor
  component: () => Promise<unknown>
  keywords?: string[]
  features?: ToolFeatureDefinition[]
  tags?: string[]
  hotkey?: string
  capabilities?: ToolCapability[]
  status?: ToolStatus
  related?: string[]
}

export const domainI18nKeys: Record<ToolDomain, string> = {
  dev: 'nav.groups.common',
  text: 'nav.groups.text',
  crypto: 'nav.groups.security',
  media: 'nav.groups.media',
}

export const tools: ToolDefinition[] = [
  {
    name: 'hash',
    path: '/hash',
    i18nKey: 'tools.hash',
    domain: 'crypto',
    icon: 'i-lucide-hash',
    color: 'error',
    component: () => import('@/views/crypto/Hash.vue'),
    keywords: ['md5', 'sha1', 'sha256', 'sha512', 'sha-256', 'sha2', 'sm3', 'checksum', 'digest', 'hash', 'file hash', '哈希', '校验', '文件哈希', '文件校验', '摘要', '哈希值'],
    tags: ['security', 'file'],
    capabilities: ['text', 'file', 'worker', 'history', 'offline'],
  },
  {
    name: 'crypto',
    path: '/crypto',
    i18nKey: 'tools.crypto',
    domain: 'crypto',
    icon: 'i-lucide-lock',
    color: 'error',
    component: () => import('@/views/crypto/Crypto.vue'),
    keywords: ['aes', 'rsa', 'sm2', 'sm4', 'bcrypt', 'jwt', 'encrypt', 'decrypt', 'cipher', 'sign', 'verify', 'password', 'token', '加密', '解密', '加解密', '国密', '签名', '验签', '密码', '令牌'],
    features: [
      { labelKey: 'tools.crypto.aes', keywords: ['aes', 'aes encrypt', 'aes decrypt', 'aes 加密', 'aes 解密'], query: { tab: 'aes' } },
      { labelKey: 'tools.crypto.sm2', keywords: ['sm2', 'sm2 encrypt', 'sm2 decrypt', 'sm2 sign', 'sm2 verify', 'sm2 国密', '国密非对称'], query: { tab: 'sm2' } },
      { labelKey: 'tools.crypto.rsa', keywords: ['rsa', 'rsa encrypt', 'rsa decrypt', 'rsa 加密', 'rsa 解密', '非对称加密'], query: { tab: 'rsa' } },
      { labelKey: 'tools.crypto.jwt', keywords: ['jwt', 'jwt encode', 'jwt decode', 'jwt sign', 'jwt verify', 'jwt 解析', 'jwt 编解码'], query: { tab: 'jwt' } },
      { labelKey: 'tools.crypto.bcrypt', keywords: ['bcrypt', 'password hash', 'password verify', '密码哈希', '密码验证'], query: { tab: 'bcrypt' } },
      { labelKey: 'tools.crypto.sm4', keywords: ['sm4', 'sm4 encrypt', 'sm4 decrypt', 'sm4 国密', '国密对称'], query: { tab: 'sm4' } },
    ],
    tags: ['security', 'format'],
    capabilities: ['text', 'worker', 'history', 'offline'],
  },
  {
    name: 'json',
    path: '/json',
    i18nKey: 'tools.json',
    domain: 'dev',
    icon: 'i-lucide-braces',
    color: 'primary',
    component: () => import('@/views/dev/JsonEditor.vue'),
    keywords: ['json', 'format', 'validate', 'jwt', 'formatter', 'prettify', 'beautify', 'minify', 'escape', 'unescape', 'tree', 'json format', 'json validate', 'jwt decode', '格式化', '验证', '美化', '压缩', '校验', '转义', '反转义', '解析 jwt', 'json 格式化', 'json 校验'],
    tags: ['format', 'dev'],
    capabilities: ['text', 'history', 'offline'],
    hotkey: 'J',
    related: ['api-debugger', 'regex', 'base64'],
  },
  {
    name: 'api-debugger',
    path: '/api-debugger',
    i18nKey: 'tools.apiDebugger',
    domain: 'dev',
    icon: 'i-lucide-send',
    color: 'info',
    component: () => import('@/views/dev/ApiDebugger.vue'),
    keywords: ['api', 'http', 'https', 'request', 'response', 'debug', 'curl', 'rest', 'fetch', 'xhr', 'postman', 'network', '接口', '调试', '请求', '响应', '接口测试', '接口调试', '发请求', '调接口', '请求头'],
    features: [
      { labelKey: 'tools.apiDebugger.queryParams', keywords: ['query params', 'url params', 'parameters', '查询参数', '请求参数', '参数'], query: { tab: 'query' } },
      { labelKey: 'tools.apiDebugger.headers', keywords: ['headers', 'request headers', 'http headers', '请求头', 'header'], query: { tab: 'headers' } },
      { labelKey: 'tools.apiDebugger.body', keywords: ['body', 'request body', 'json body', 'form body', '请求体', 'json 请求体', '表单请求体'], query: { tab: 'body' } },
    ],
    tags: ['dev', 'http'],
    capabilities: ['text', 'history', 'offline'],
  },
  {
    name: 'timestamp',
    path: '/timestamp',
    i18nKey: 'tools.timestamp',
    domain: 'dev',
    icon: 'i-lucide-clock',
    color: 'warning',
    component: () => import('@/views/dev/Timestamp.vue'),
    keywords: ['timestamp', 'timezone', 'date', 'unix', 'epoch', 'time convert', 'date diff', 'utc', 'milliseconds', 'seconds', '时间戳', '时区', '日期', '时间转换', '日期计算', '时间差', '时差', 'Unix 时间', '毫秒', '秒级'],
    tags: ['convert', 'dev'],
    capabilities: ['text', 'history', 'offline'],
  },
  {
    name: 'random',
    path: '/random',
    i18nKey: 'tools.random',
    domain: 'dev',
    icon: 'i-lucide-shuffle',
    color: 'secondary',
    component: () => import('@/views/dev/RandomData.vue'),
    keywords: ['random', 'uuid', 'faker', 'phone', 'email', 'password', 'id card', 'bank card', 'ip', 'mac', 'mock data', 'test data', '生成', '随机', '假数据', '测试数据', '手机号', '身份证', '银行卡', '邮箱', '随机密码'],
    tags: ['generate', 'dev'],
    capabilities: ['text', 'offline'],
  },
  {
    name: 'scoreboard',
    path: '/scoreboard',
    i18nKey: 'tools.scoreboard',
    domain: 'dev',
    icon: 'i-lucide-trophy',
    color: 'warning',
    component: () => import('@/views/dev/Scoreboard.vue'),
    keywords: ['scoreboard', 'score', 'team', 'counter', 'match', 'game', 'points', '计分', '比赛', '记分牌', '比分', '计数', '加分', '减分', '计分器'],
    tags: ['utility', 'dev'],
    capabilities: ['text', 'offline'],
  },
  {
    name: 'timer',
    path: '/timer',
    i18nKey: 'tools.timer',
    domain: 'dev',
    icon: 'i-lucide-timer',
    color: 'primary',
    component: () => import('@/views/dev/TimerTool.vue'),
    keywords: ['timer', 'countdown', 'clock', 'alarm', 'reminder', '计时器', '倒计时', '倒数', '闹钟', '提醒', '计时'],
    tags: ['utility', 'dev'],
    capabilities: ['text', 'offline'],
  },
  {
    name: 'pomodoro',
    path: '/pomodoro',
    i18nKey: 'tools.pomodoro',
    domain: 'dev',
    icon: 'i-lucide-timer-reset',
    color: 'error',
    component: () => import('@/views/dev/PomodoroTool.vue'),
    keywords: ['pomodoro', 'focus', 'timer', 'break', 'work session', 'productivity', '番茄钟', '番茄工作法', '专注', '休息', '专注计时', '工作计时'],
    tags: ['utility', 'dev'],
    capabilities: ['text', 'offline'],
  },
  {
    name: 'picker',
    path: '/picker',
    i18nKey: 'tools.picker',
    domain: 'dev',
    icon: 'i-lucide-list-checks',
    color: 'secondary',
    component: () => import('@/views/dev/RandomPicker.vue'),
    keywords: ['picker', 'random pick', 'lottery', 'choice', 'draw', 'raffle', 'roll', '抽取', '随机选择', '抽奖', '抽签', '点名', '随机点名', '摇号', '选择困难'],
    tags: ['utility', 'dev'],
    capabilities: ['text', 'offline'],
  },
  {
    name: 'calculator',
    path: '/calculator',
    i18nKey: 'tools.calculator',
    domain: 'dev',
    icon: 'i-lucide-calculator',
    color: 'info',
    component: () => import('@/views/dev/CalculatorTool.vue'),
    keywords: ['calculator', 'math', 'calculate', 'expression', 'arithmetic', '算术', '计算器', '计算', '四则运算', '表达式', '数学'],
    tags: ['utility', 'dev'],
    capabilities: ['text', 'offline'],
  },
  {
    name: 'unit',
    path: '/unit',
    i18nKey: 'tools.unit',
    domain: 'dev',
    icon: 'i-lucide-ruler',
    color: 'primary',
    component: () => import('@/views/dev/UnitConverter.vue'),
    keywords: ['unit', 'convert', 'converter', 'length', 'weight', 'mass', 'temperature', '单位换算', '单位转换', '换算', '长度', '重量', '质量', '温度'],
    features: [
      { labelKey: 'tools.unit.categories.length', keywords: ['length', 'distance', '长度', '距离'], query: { category: 'length' } },
      { labelKey: 'tools.unit.categories.weight', keywords: ['weight', 'mass', '重量', '质量'], query: { category: 'weight' } },
      { labelKey: 'tools.unit.categories.temperature', keywords: ['temperature', 'celsius', 'fahrenheit', 'kelvin', '温度', '摄氏度', '华氏度'], query: { category: 'temperature' } },
    ],
    tags: ['convert', 'dev'],
    capabilities: ['text', 'offline'],
  },
  {
    name: 'bmi',
    path: '/bmi',
    i18nKey: 'tools.bmi',
    domain: 'dev',
    icon: 'i-lucide-heart-pulse',
    color: 'success',
    component: () => import('@/views/dev/BmiTool.vue'),
    keywords: ['bmi', 'health', 'body mass index', 'height', 'weight', 'fitness', '体重指数', '身高', '体重', '健康', '肥胖', 'BMI 计算'],
    tags: ['utility', 'dev'],
    capabilities: ['text', 'offline'],
  },
  {
    name: 'base',
    path: '/base',
    i18nKey: 'tools.base',
    domain: 'dev',
    icon: 'i-lucide-binary',
    color: 'secondary',
    component: () => import('@/views/dev/BaseConverter.vue'),
    keywords: ['base convert', 'radix', 'binary', 'octal', 'decimal', 'hex', 'hexadecimal', 'number convert', '进制转换', '进制', '二进制', '八进制', '十进制', '十六进制', '数字转换'],
    tags: ['convert', 'dev'],
    capabilities: ['text', 'offline'],
  },
  {
    name: 'markdown',
    path: '/markdown',
    i18nKey: 'tools.markdown',
    domain: 'dev',
    icon: 'i-lucide-file-text',
    color: 'primary',
    component: () => import('@/views/dev/MarkdownTool.vue'),
    keywords: ['markdown', 'md', 'preview', 'editor', 'html', 'document', 'write', 'markdown 编辑', 'md 编辑', '预览', '文档', '写作', '说明文档'],
    tags: ['editor', 'dev'],
    capabilities: ['text', 'offline'],
    related: ['latex', 'mermaid'],
  },
  {
    name: 'latex',
    path: '/latex',
    i18nKey: 'tools.latex',
    domain: 'dev',
    icon: 'i-lucide-square-function',
    color: 'secondary',
    component: () => import('@/views/dev/LatexTool.vue'),
    keywords: ['latex', 'tex', 'math', 'formula', 'equation', 'katex', 'mathjax', '公式', '数学', '公式编辑', '数学公式', '方程', 'TeX'],
    tags: ['editor', 'math', 'dev'],
    capabilities: ['text', 'offline'],
    related: ['markdown', 'mermaid'],
  },
  {
    name: 'mermaid',
    path: '/mermaid',
    i18nKey: 'tools.mermaid',
    domain: 'dev',
    icon: 'i-lucide-git-branch-plus',
    color: 'info',
    component: () => import('@/views/dev/MermaidTool.vue'),
    keywords: ['mermaid', 'diagram', 'flowchart', 'sequence', 'chart', 'class diagram', 'gantt', 'mindmap', 'architecture', '流程图', '图表', '时序图', '序列图', '类图', '甘特图', '架构图'],
    tags: ['editor', 'diagram', 'dev'],
    capabilities: ['text', 'offline'],
    related: ['markdown', 'latex'],
  },
  {
    name: 'diagrams',
    path: '/diagrams',
    i18nKey: 'tools.diagrams',
    domain: 'dev',
    icon: 'i-lucide-workflow',
    color: 'info',
    component: () => import('@/views/dev/DiagramsTool.vue'),
    keywords: ['diagrams.net', 'draw.io', 'drawio', 'diagram', 'flowchart', 'uml', 'architecture', 'mind map', 'wireframe', '流程图', '图表', '架构图', 'UML', '思维导图', '原型图', '网络拓扑'],
    tags: ['editor', 'diagram', 'external'],
    related: ['mermaid', 'markdown'],
  },
  {
    name: 'geogebra',
    path: '/geogebra',
    i18nKey: 'tools.geogebra',
    domain: 'dev',
    icon: 'i-lucide-shapes',
    color: 'secondary',
    component: () => import('@/views/dev/GeoGebraTool.vue'),
    keywords: ['geogebra', 'geogebra classic', 'geometry', 'graphing', 'math', 'algebra', 'function graph', 'calculator', '3d math', '几何画板', '动态几何', '函数图像', '数学', '代数', '图形计算器', '数学绘图'],
    tags: ['editor', 'math', 'geometry', 'external'],
    related: ['calculator', 'latex', 'mermaid'],
  },
  {
    name: 'js-sandbox',
    path: '/js-sandbox',
    i18nKey: 'tools.jsSandbox',
    domain: 'dev',
    icon: 'i-lucide-square-terminal',
    color: 'warning',
    component: () => import('@/views/dev/JsSandboxTool.vue'),
    keywords: ['javascript', 'sandbox', 'runner', 'js', 'code', 'console', 'snippet', '脚本沙盒', '运行 js', '代码运行', '脚本', '控制台', '片段'],
    tags: ['editor', 'dev'],
    capabilities: ['text', 'offline'],
  },
  {
    name: 'cron',
    path: '/cron',
    i18nKey: 'tools.cron',
    domain: 'dev',
    icon: 'i-lucide-calendar-clock',
    color: 'info',
    component: () => import('@/views/dev/CronParserTool.vue'),
    keywords: ['cron', 'schedule', 'scheduler', 'parser', 'crontab', 'next run', '定时表达式', '定时任务', '计划任务', '表达式', '下次执行', 'cron 解析'],
    tags: ['parser', 'dev'],
    capabilities: ['text', 'offline'],
  },
  {
    name: 'color',
    path: '/color',
    i18nKey: 'tools.color',
    domain: 'dev',
    icon: 'i-lucide-palette',
    color: 'primary',
    component: () => import('@/views/dev/ColorTool.vue'),
    keywords: ['color', 'hex', 'rgb', 'rgba', 'hsl', 'hsla', 'picker', 'palette', 'eyedropper', 'css color', '颜色', '调色板', '取色', '颜色转换', '色值', '调色', '配色'],
    tags: ['convert', 'dev'],
    capabilities: ['text', 'offline'],
  },
  {
    name: 'base64',
    path: '/base64',
    i18nKey: 'tools.base64',
    domain: 'text',
    icon: 'i-lucide-code',
    color: 'success',
    component: () => import('@/views/text/Base64.vue'),
    keywords: ['base64', 'b64', 'encode', 'decode', 'data uri', 'file base64', 'image base64', '编码', '解码', 'base64 编码', 'base64 解码', '图片 base64', '文件 base64', '转码'],
    features: [
      { labelKey: 'tools.base64.encode', keywords: ['encode', 'base64 encode', 'text to base64', 'file to base64', '编码', 'base64 编码', '文件转 base64'], query: { mode: 'encode' } },
      { labelKey: 'tools.base64.decode', keywords: ['decode', 'base64 decode', 'base64 to text', 'image preview', '解码', 'base64 解码', '图片预览'], query: { mode: 'decode' } },
    ],
    tags: ['convert', 'format'],
    capabilities: ['text', 'file', 'image', 'history', 'offline'],
  },
  {
    name: 'encoding',
    path: '/encoding',
    i18nKey: 'tools.encoding',
    domain: 'text',
    icon: 'i-lucide-type',
    color: 'info',
    component: () => import('@/views/text/Encoding.vue'),
    keywords: ['unicode', 'gbk', 'utf8', 'utf-8', 'url encode', 'url decode', 'html entity', 'escape', 'hex', '编码转换', '字符集', '字符编码', 'URL 编码', 'URL 解码', 'unicode 解码', '乱码', '实体编码'],
    features: [
      { labelKey: 'tools.encoding.charToEncode', keywords: ['encode', 'char to encode', 'unicode encode', 'url encode', 'html entity encode', '字符转编码', '编码'], query: { mode: 'to' } },
      { labelKey: 'tools.encoding.encodeToChar', keywords: ['decode', 'encode to char', 'unicode decode', 'url decode', 'html entity decode', '编码转字符', '解码'], query: { mode: 'from' } },
    ],
    tags: ['convert'],
    capabilities: ['text', 'history', 'offline'],
  },
  {
    name: 'morse',
    path: '/morse',
    i18nKey: 'tools.morse',
    domain: 'text',
    icon: 'i-lucide-radio-tower',
    color: 'warning',
    component: () => import('@/views/text/MorseTool.vue'),
    keywords: ['morse', 'code', 'encode', 'decode', 'telegraph', 'sos', '莫斯电码', '摩斯电码', '莫尔斯', '电报码', 'SOS'],
    features: [
      { labelKey: 'tools.morse.encode', keywords: ['morse encode', 'text to morse', '莫斯编码', '文本转莫斯'], query: { mode: 'encode' } },
      { labelKey: 'tools.morse.decode', keywords: ['morse decode', 'morse to text', '莫斯解码', '莫斯转文本'], query: { mode: 'decode' } },
    ],
    tags: ['convert', 'text'],
    capabilities: ['text', 'offline'],
  },
  {
    name: 'bigtext',
    path: '/bigtext',
    i18nKey: 'tools.bigtext',
    domain: 'text',
    icon: 'i-lucide-database',
    color: 'secondary',
    component: () => import('@/views/text/BigTextTool.vue'),
    keywords: ['big text', 'large text', 'stats', 'dedupe', 'sort', 'chunk', 'line tools', 'text stats', '大文本处理', '大文本', '文本统计', '去重', '排序', '分块', '行处理'],
    features: [
      { labelKey: 'tools.bigtext.modes.stats', keywords: ['stats', 'text stats', 'count lines', '统计', '文本统计', '行数统计'], query: { mode: 'stats' } },
      { labelKey: 'tools.bigtext.modes.dedupe', keywords: ['dedupe', 'unique lines', 'remove duplicates', '去重', '行去重'], query: { mode: 'dedupe' } },
      { labelKey: 'tools.bigtext.modes.sort', keywords: ['sort', 'sort lines', '排序', '行排序'], query: { mode: 'sort' } },
      { labelKey: 'tools.bigtext.modes.chunk', keywords: ['chunk', 'split chunks', '分块', '文本分块'], query: { mode: 'chunk' } },
    ],
    tags: ['text', 'utility'],
    capabilities: ['text', 'offline'],
  },
  {
    name: 'regex',
    path: '/regex',
    i18nKey: 'tools.regex',
    domain: 'text',
    icon: 'i-lucide-regex',
    color: 'warning',
    component: () => import('@/views/text/Regex.vue'),
    keywords: ['regex', 'regexp', 'regular expression', 'pattern', 'match', 'replace', 'split', 'test', 'extract', '正则', '正则表达式', '正则测试', '正则匹配', '提取', '替换', '分割'],
    features: [
      { labelKey: 'tools.regex.match', keywords: ['match', 'test regex', 'extract matches', '匹配', '正则匹配', '提取'], query: { tab: 'match' } },
      { labelKey: 'tools.regex.replace', keywords: ['replace', 'regex replace', '替换', '正则替换'], query: { tab: 'replace' } },
      { labelKey: 'tools.regex.split', keywords: ['split', 'regex split', '分割', '正则分割'], query: { tab: 'split' } },
    ],
    tags: ['dev'],
    capabilities: ['text', 'history', 'offline'],
  },
  {
    name: 'diff',
    path: '/diff',
    i18nKey: 'tools.diff',
    domain: 'text',
    icon: 'i-lucide-file-diff',
    color: 'neutral',
    component: () => import('@/views/text/DiffTool.vue'),
    keywords: ['diff', 'compare', 'merge', 'text compare', 'image compare', 'side by side', 'difference', '对比', '比较', '文本差异', '文本对比', '图片对比', '差异', '合并'],
    features: [
      { labelKey: 'tools.diff.textDiff', keywords: ['text diff', 'text compare', '文本对比', '文本差异'], query: { tab: 'text' } },
      { labelKey: 'tools.diff.imageDiff', keywords: ['image diff', 'image compare', '图片对比', '图片差异'], query: { tab: 'image' } },
      { labelKey: 'tools.diff.sideBySide', keywords: ['side by side', '并排对比'], query: { tab: 'image', mode: 'side' } },
      { labelKey: 'tools.diff.overlay', keywords: ['overlay', '叠加对比'], query: { tab: 'image', mode: 'overlay' } },
    ],
    tags: ['compare', 'dev'],
    capabilities: ['text', 'image', 'offline'],
  },
  {
    name: 'string',
    path: '/string',
    i18nKey: 'tools.string',
    domain: 'text',
    icon: 'i-lucide-case-sensitive',
    color: 'secondary',
    component: () => import('@/views/text/StringTool.vue'),
    keywords: ['string', 'case', 'camel', 'pascal', 'snake', 'kebab', 'trim', 'uppercase', 'lowercase', '文本处理', '字符串', '大小写', '驼峰', '帕斯卡', '下划线', '短横线', '去空格'],
    features: [
      { labelKey: 'tools.string.results.upper', keywords: ['uppercase', 'upper case', '全大写', '大写'], query: { result: 'upper' } },
      { labelKey: 'tools.string.results.lower', keywords: ['lowercase', 'lower case', '全小写', '小写'], query: { result: 'lower' } },
      { labelKey: 'tools.string.results.title', keywords: ['title case', '标题格式'], query: { result: 'title' } },
      { labelKey: 'tools.string.results.camel', keywords: ['camel', 'camelcase', 'camelCase', '驼峰'], query: { result: 'camel' } },
      { labelKey: 'tools.string.results.pascal', keywords: ['pascal', 'pascalcase', 'PascalCase', '帕斯卡'], query: { result: 'pascal' } },
      { labelKey: 'tools.string.results.snake', keywords: ['snake', 'snake_case', '下划线'], query: { result: 'snake' } },
      { labelKey: 'tools.string.results.kebab', keywords: ['kebab', 'kebab-case', '短横线'], query: { result: 'kebab' } },
      { labelKey: 'tools.string.results.trimmed', keywords: ['trim', '去首尾空白'], query: { result: 'trimmed' } },
      { labelKey: 'tools.string.results.collapsed', keywords: ['collapse whitespace', '折叠空白'], query: { result: 'collapsed' } },
      { labelKey: 'tools.string.results.uniqueLines', keywords: ['unique lines', 'dedupe lines', '行去重'], query: { result: 'uniqueLines' } },
      { labelKey: 'tools.string.results.sortedLines', keywords: ['sort lines', '行排序'], query: { result: 'sortedLines' } },
      { labelKey: 'tools.string.results.reversedLines', keywords: ['reverse lines', '行反转'], query: { result: 'reversedLines' } },
    ],
    tags: ['convert', 'text'],
    capabilities: ['text', 'history', 'offline'],
  },
  {
    name: 'qrcode',
    path: '/qrcode',
    i18nKey: 'tools.qrcode',
    domain: 'media',
    icon: 'i-lucide-qr-code',
    color: 'primary',
    component: () => import('@/views/media/Qrcode.vue'),
    keywords: ['qrcode', 'qr', 'qr code', 'barcode', 'scan', 'generate qr', 'parse qr', '二维码', '二维码生成', '二维码解析', '条码', '扫码', '识别二维码'],
    features: [
      { labelKey: 'tools.qrcode.generate', keywords: ['generate qr', 'qr generator', '二维码生成', '生成二维码'], query: { tab: 'generate' } },
      { labelKey: 'tools.qrcode.parse', keywords: ['parse qr', 'scan qr', 'decode qr', '二维码解析', '识别二维码', '扫码'], query: { tab: 'parse' } },
    ],
    tags: ['generate', 'media'],
    capabilities: ['text', 'image', 'file', 'offline'],
  },
  {
    name: 'image',
    path: '/image',
    i18nKey: 'tools.image',
    domain: 'media',
    icon: 'i-lucide-image',
    color: 'success',
    component: () => import('@/views/media/ImageTool.vue'),
    keywords: ['image', 'photo', 'compress', 'resize', 'crop', 'watermark', 'convert', 'phantom tank', 'stitch', 'gif', 'metadata', 'editor', '图片', '照片', '压缩', '裁剪', '缩放', '水印', '图片转换', '转格式', '幻影坦克', '拼接', '拼图', '动图', '图片信息'],
    features: [
      { labelKey: 'tools.image.batchOps.compress', keywords: ['image compress', 'compress image', '图片压缩', '压缩'], query: { mode: 'batch', batch: 'compress' } },
      { labelKey: 'tools.image.batchOps.format', keywords: ['image format', 'convert image', '图片格式转换', '转格式'], query: { mode: 'batch', batch: 'format' } },
      { labelKey: 'tools.image.batchOps.resize', keywords: ['image resize', 'resize image', '图片缩放', '尺寸修改', '缩放'], query: { mode: 'batch', batch: 'resize' } },
      { labelKey: 'tools.image.batchOps.watermark', keywords: ['image watermark', 'watermark image', '图片水印', '添加水印'], query: { mode: 'batch', batch: 'watermark' } },
      { labelKey: 'tools.image.batchOps.rotate', keywords: ['image rotate', 'rotate image', '图片旋转', '旋转'], query: { mode: 'batch', batch: 'rotate' } },
      { labelKey: 'tools.image.batchOps.crop', keywords: ['image crop', 'crop image', '图片裁剪', '裁剪'], query: { mode: 'batch', batch: 'crop' } },
      { labelKey: 'tools.image.labOps.phantom', keywords: ['phantom tank', '幻影坦克'], query: { mode: 'lab', lab: 'phantom' } },
      { labelKey: 'tools.image.labOps.stitch', keywords: ['stitch image', 'image stitch', '图片拼接', '拼图', '长图拼接'], query: { mode: 'lab', lab: 'stitch' } },
      { labelKey: 'tools.image.labOps.metadata', keywords: ['image metadata', 'exif', '图片信息', '元数据'], query: { mode: 'lab', lab: 'metadata' } },
      { labelKey: 'tools.image.labOps.gif', keywords: ['gif', 'images to gif', 'gif maker', '图片转 gif', '动图'], query: { mode: 'lab', lab: 'gif' } },
      { labelKey: 'tools.image.labOps.editor', keywords: ['image editor', 'visual editor', '图片编辑', '可视编辑'], query: { mode: 'lab', lab: 'editor' } },
    ],
    tags: ['convert', 'media', 'gif', 'editor'],
    capabilities: ['image', 'file', 'offline'],
  },
  {
    name: 'pdf',
    path: '/pdf',
    i18nKey: 'tools.pdf',
    domain: 'media',
    icon: 'i-lucide-file-text',
    color: 'error',
    component: () => import('@/views/media/PdfTool.vue'),
    keywords: ['pdf', 'merge', 'split', 'extract', 'compress', 'watermark', 'to image', 'merge pdf', 'split pdf', 'pdf 合并', 'pdf 拆分', 'PDF 压缩', 'PDF 水印', 'PDF 转图片', '页面提取'],
    features: [
      { labelKey: 'tools.pdf.compress', keywords: ['compress pdf', 'pdf compress', 'pdf 压缩', '压缩 pdf'], query: { tab: 'compress' } },
      { labelKey: 'tools.pdf.merge', keywords: ['merge pdf', 'pdf merge', 'pdf 合并', '合并 pdf'], query: { tab: 'merge' } },
      { labelKey: 'tools.pdf.split', keywords: ['split pdf', 'pdf split', 'extract pages', 'pdf 拆分', '拆分 pdf', '页面提取'], query: { tab: 'split' } },
      { labelKey: 'tools.pdf.watermark', keywords: ['pdf watermark', 'watermark pdf', 'pdf 水印', '添加水印'], query: { tab: 'watermark' } },
      { labelKey: 'tools.pdf.toImage', keywords: ['pdf to image', 'pdf to png', 'pdf 转图片', '转图片'], query: { tab: 'toImage' } },
    ],
    tags: ['convert', 'media', 'file'],
    capabilities: ['pdf', 'file', 'worker', 'offline'],
  },
]

export function getToolFeaturePath(tool: ToolDefinition, feature?: ToolFeatureDefinition) {
  if (!feature?.query) return tool.path
  const query = Object.entries(feature.query)
    .map(([key, value]) => `${encodeURIComponent(key)}=${encodeURIComponent(value)}`)
    .join('&')
  return query ? `${tool.path}?${query}` : tool.path
}

export const toolsByName = new Map(tools.map((tool) => [tool.name, tool]))
export const toolsByPath = new Map(tools.map((tool) => [tool.path, tool]))
export const toolsByDomain = tools.reduce((groups, tool) => {
  groups[tool.domain].push(tool)
  return groups
}, { dev: [], text: [], crypto: [], media: [] } as Record<ToolDomain, ToolDefinition[]>)

export const offlineTools = tools.filter((tool) => tool.capabilities?.includes('offline'))
export const workerTools = tools.filter((tool) => tool.capabilities?.includes('worker'))

export function createToolRoutes(): RouteRecordRaw[] {
  return tools.map((tool) => ({
    path: tool.path,
    name: tool.name,
    component: tool.component,
    meta: {
      domain: tool.domain,
      i18nKey: tool.i18nKey,
      keywords: tool.keywords,
      tags: tool.tags,
    },
  }))
}
